[mongodb]
uri = "mongodb+srv://amitvad:dEy5vKTRpp8Fg0g9@cluster0.ww7u6.mongodb.net/"
database = "myDatabase"
clusters_collection = "oem_clusters"
claims_collection = "oem_claims"

[api]
google_api_key = "AIzaSyDzqu-HkZz-gpNYSQBd64lz56qpeK4O-MI"

[model]
sentence_transformer = "nomic-ai/nomic-embed-text-v1"
gemini_model = "gemini-1.5-flash"

[app]
title = "Cluster Finder for issues"
image_path = "./issue sphere.jpg"
image_width = 150